### ISSUE TITLE
Dev mode button on top of the screen so we can use it on Linux?

### ISSUE THREAD

**Issue by ghost** [m00nl1ght-dev/HugsLogPublisher#1]

**Comment by m00nl1ght-dev** [comment]
What is currently the problem on Linux? Does the keybind not work?

**Comment by ghost** [comment]
Yep, and there's no sense to create workaround and finding reason, button looks like the best long-term solution, because it was fixed before...

**Comment by m00nl1ght-dev** [comment]
Alright, I'll look into it.

**Comment by ghost** [comment]
And your mod will have sense like addon for HugsLib this way :D

**Comment by m00nl1ght-dev** [comment]
Added in latest version (button in vanilla log window)
